remote_theme: riggraz/no-style-please
timezone: Asia/Shanghai
encoding: utf-8
markdown: GFM

title: odorajbotoj's blog
author: odorajbotoj
email: odorajbotoj@163.com
url: odorajbotoj.github.io

favicon: "logo.png"

theme_config:
  appearance: "auto"
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  lowercase_titles: true

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jektex

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]
